In [11]:
import pandas as pd

def calculate_quarterly_returns(data):
    data['Dates'] = pd.to_datetime(data['Dates'])
    data.set_index('Dates', inplace=True)

    # Calculate weekly returns
    weekly_returns = data.pct_change()

    # Calculate quarterly returns
    quarterly_returns = weekly_returns.rolling(window=4).agg(lambda x: (1 + x).prod() - 1)

    return quarterly_returns

# Read the dataset from Excel file
df = pd.read_csv("industry.csv")

# Calculate Quarterly Returns
quarterly_returns_df = calculate_quarterly_returns(df)
display(quarterly_returns_df)

,S&P500,Healthcare,Materials,Financials,Consumer Discretionary,Consumer Staples,Information Technology,Utilities,Energy,Industrials
Dates,,,,,,,,,,
1999-11-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999-11-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999-11-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999-11-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999-12-03,0.047355,-0.027343,0.010516,-0.036746,0.038062,0.055157,0.064208,-0.056870,0.099885,0.016237
...,...,...,...,...,...,...,...,...,...,...
2022-11-04,0.036886,0.066883,0.085956,0.098149,-0.038312,0.081129,-0.073058,0.052610,0.116955,0.116136
2022-11-11,0.115500,0.076555,0.192118,0.158870,0.062466,0.091136,0.031672,0.096608,0.160501,0.175264
2022-11-18,0.058356,0.063153,0.105562,0.098673,-0.025743,0.085267,-0.018531,0.087225,0.053881,0.121122
2022-11-25,0.033816,0.032459,0.101521,0.056843,-0.021560,0.044313,0.020471,0.052843,0.027946,0.070418
2022-12-02,0.081933,0.069094,0.110674,0.059128,0.061420,0.077087,0.139003,0.059218,-0.015235,0.076874